
apiVersion: batch/v1
kind: Job
metadata:
  name: merowinger-quote
spec:
  template:
    spec:
      containers:
      - name: quote
        image: busybox
        command: ["sh", "-c", "echo 'Es ist die Frage der Ursache und Wirkung. Das ist es, was wir hier haben.'"]
      restartPolicy: Never
  backoffLimit: 1
