
apiVersion: batch/v1
kind: Job
metadata:
  name: merowinger-quote-job
spec:
  completions: 1             # Anzahl der erfolgreichen Durchl채ufe bis Job abgeschlossen ist
  parallelism: 1             # Wie viele Pods gleichzeitig laufen d체rfen
  backoffLimit: 3            # Max. Fehlversuche pro Pod vor Abbruch
  ttlSecondsAfterFinished: 60  # Lebensdauer des Jobs nach Abschluss (Sekunden)
  activeDeadlineSeconds: 120   # Maximale Zeit f체r Job-Ausf체hrung (Sekunden)
  template:
    spec:
      containers:
      - name: quote
        image: busybox
        command: ["sh", "-c", "echo 'Wissen ist nicht das Problem. Das Problem ist der Glaube.'"]
      restartPolicy: OnFailure   # Restart nur bei Fehlschlag erlaubt
