kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-dev-cluster
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
      endpoint = ["http://localhost:5001"]
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
  - role: worker
    image: kindest/node:v1.33.1
    labels:
      worker: worker-0
  - role: worker
    image: kindest/node:v1.33.1
    labels:
      worker: worker-1
