kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-dev-cluster
# Ermöglicht Zugriff auf lokale Docker-Registry via "localhost:5001"
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
nodes:
  - role: control-plane
    image: kindest/node:v1.32.5
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
  - role: worker
    image: kindest/node:v1.32.5
    labels:
      worker: worker-0
  - role: worker
    image: kindest/node:v1.32.5
    labels:
      worker: worker-1
