kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-dev-cluster
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    labels:
      controll-plane: true
  - role: worker
    image: kindest/node:v1.33.1
    labels:
      worker: worker-0
  - role: worker
    image: kindest/node:v1.33.1
    labels:
      worker: worker-1
