apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentsmith-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentsmith
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sh", "-c", "while true; do echo 'Hello, Mr. Anderson'; sleep 1; done"]
