apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-app
  template:
    metadata:
      labels:
        app: http-app
    spec:
      containers:
      - name: http-app
        image: localhost:5001/http-app:1.1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
