apiVersion: v1
kind: Service
metadata:
  name: http-app
spec:
  selector:
    app: http-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080         # Zugriff über http://localhost:30080
  type: NodePort
